
INSERT INTO IconDefinitions (Name,Atlas,'Index') 
SELECT 'ICON_BELIEF_KING_OF_THE_GODS', 'ICON_ATLAS_BELIEFS_PATHEON', 5 WHERE 'ICON_BELIEF_KING_OF_THE_GODS' NOT IN (SELECT Name FROM IconDefinitions) Union
SELECT 'ICON_BELIEF_KING_OF_THE_GODS_FOLLOWER', 'ICON_ATLAS_BELIEFS_PATHEON', 23 WHERE 'ICON_BELIEF_KING_OF_THE_GODS_FOLLOWER' NOT IN (SELECT Name FROM IconDefinitions) Union
SELECT 'ICON_BELIEF_KING_OF_THE_GODS_FOUNDER', 'ICON_ATLAS_BELIEFS_PATHEON', 24 WHERE 'ICON_BELIEF_KING_OF_THE_GODS_FOUNDER' NOT IN (SELECT Name FROM IconDefinitions) Union
SELECT 'ICON_BELIEF_KING_OF_THE_GODS_ENHANCER', 'ICON_ATLAS_BELIEFS_PATHEON', 25 WHERE 'ICON_BELIEF_KING_OF_THE_GODS_ENHANCER' NOT IN (SELECT Name FROM IconDefinitions);		
